# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aprende a Programar com o Scratch!
email: livroscratch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  O sítio web onde podes encontrar recursos para aprenderes a programar em Scratch!
  Nele encontras, por exemplo, todas as páginas de apoio ao livro «Cria o teu próprio
  jogo de computador».
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scratch.pt" # the base hostname & protocol for your site
twitter_username: livroscratch
github_username:  livroscratch

# Build settings
markdown: kramdown

# Other settings:
timezone: Europe/Lisbon
