title: Cria o Teu Jogo de Computador
email: livroscratch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sítio web do livro Cria o Teu Jogo de Computador
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: livroscratch
github_username:  livroscratch
lang: pt-PT
disqus:
  shortname: scratchpt

# Build settings
markdown: kramdown
theme: minima

# Collections:
collections:
  chapters:
    output: true
  resources:
    output: true

# Gems:
gems:
  - jekyll-redirect-from